### ISSUE TITLE
关于CAG和DDE模块的代码

### ISSUE THREAD

**Issue by hongyugege** [sillymistake/CAG-DDE#1]
您好，在您的代码中  我没有看到这两个模块的具体原代码，求指点

**Comment by sillymistake** [comment]
CAG和DDE分别对应ours_pair.py中的PredBlock和DualRefine

**Comment by sillymistake** [comment]
> 您好，在您的代码中 我没有看到这两个模块的具体原代码，求指点

CAG和DDE分别对应ours_pair.py中的PredBlock和DualRefine

**Comment by hongyugege** [comment]
好的 找到了 谢谢您哈
