### ISSUE TITLE
作者您好，向你请教关于训练代码的问题

### ISSUE THREAD

**Issue by zhangyusen2020** [sillymistake/CAG-DDE#2]
我看训练代码里有一个freeze_bn函数，我理解的是冻结bn层的参数。请问这个该怎么使用呢，训练的时候注释掉这个对效果会有影响吗？还有就是跑出来的S，F，MAE和最后用MATLAB测的指标有时候会差很多，请问你们也是这样吗？还请不吝赐教，谢谢。

**Comment by sillymistake** [comment]
> 我看训练代码里有一个freeze_bn函数，我理解的是冻结bn层的参数。请问这个该怎么使用呢，训练的时候注释掉这个对效果会有影响吗？还有就是跑出来的S，F，MAE和最后用MATLAB测的指标有时候会差很多，请问你们也是这样吗？还请不吝赐教，谢谢。

freeze_bn函数是用于在VSOD数据集上finetinue的时候冻结bn层参数，从实验结果来看，冻不冻结基本没影响。metric.py中的指标计算函数来自 https://github.com/lartpang/Py-SOD-VOS-EvalToolkit 。只是用于观察大概的效果。其跑出来的S，F与 https://github.com/DengPingFan/DAVSOD/blob/master/EvaluateTool 中的代码相比会偏高，mae基本一样。为了公平比较，仍需要生成显著图，然后用matlab代码测试。

**Comment by zhangyusen2020** [comment]
多谢解答，万分感谢。
